[[manager.prepend_keymap]]
on   = "R"
run  = "plugin rsync"
desc = "Copy files using rsync"
  
[[manager.prepend_keymap]]
on   = "T"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = "P"
run  = "plugin toggle-view --args=parent"
desc = "Toggle parent"

[[manager.prepend_keymap]]
on   = "<C-2>"
run  = "plugin toggle-view --args=current"
desc = "Toggle current"

[[manager.prepend_keymap]]
on   = "<C-3>"
run  = "plugin toggle-view --args=preview"
desc = "Toggle preview"
